# Generated by Django 6.1 on 2026-09-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, db_default='', verbose_name='descripción'),
        ),
    ]
