# Generated by Django 6.1 on 2026-09-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_alter_producto_precio_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(db_default=0),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gt', 0)), name='check_precio_mayor_a_cero'),
        ),
    ]
