# Generated by Django 6.1 on 2026-09-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_alter_producto_precio_alter_producto_stock_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='producto',
            name='check_precio_mayor_a_cero',
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='check_precio_mayor_a_cero'),
        ),
    ]
